project:
  type: book


book:
  title: "The MMJMesh Book"
  author: "Matthias Baitsch"
  chapters: 
    - index.qmd
    - mesh.qmd
    - plot.qmd

format:
  html:
    code-fold: true
  pdf:
    documentclass: scrreport
