project:
  type: book

book:
  title: "The MMJMesh Library"
  subtitle: "Minh's and Matthias' Julia Mesh Library"
  author: "Matthias Baitsch"
  chapters: 
    - index.qmd
    - mesh.qmd
    - plot.qmd
    - mathematics.qmd

format:
  html:
    css: style.css

execute:
  freeze: auto
