on:
  push:
    branches: main


name: Render and Publish

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install jupyter
      - name: Checkout
        uses: actions/checkout@v4        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
      - name: Cache Julia packages
        uses: julia-actions/cache@v1
      - name: Set up X11
        run: sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev xsettingsd x11-xserver-utils
      - name: Build
        uses: julia-actions/julia-buildpkg@v1
      - name: Test
        continue-on-error: true
        run: DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia --color=yes --project -e 'using Pkg; Pkg.test(coverage=true)'
      - name: Process code coverage information
        uses: julia-actions/julia-processcoverage@v1
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}      
          file: lcov.info
      - name: Render
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: demo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
